# Generated by Django 4.2.16 on 2025-05-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstate',
            name='lock_code',
            field=models.CharField(default='1234', max_length=16),
        ),
        migrations.AddField(
            model_name='roomstate',
            name='user_input',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
