# Generated by Django 4.2.16 on 2025-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapeapp', '0002_roomstate_lock_code_roomstate_user_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='mushrooms/')),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomState',
        ),
    ]
