# Generated by Django 4.2.16 on 2025-05-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapeapp', '0003_mushroom_delete_roomstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='image',
            field=models.ImageField(upload_to='media/mushrooms/'),
        ),
    ]
