# Generated by Django 4.2.16 on 2025-05-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapeapp', '0004_alter_mushroom_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourdoughStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('correct_order', models.IntegerField()),
            ],
        ),
    ]
