# Generated by Django 4.2.16 on 2025-05-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapeapp', '0005_sourdoughstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardgameTrivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(max_length=100)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
            ],
        ),
    ]
